name = "english-learning-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[vars]
ALLOWED_ORIGIN = "http://localhost:5173,https://english-learning-web.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "english-learning"
database_id = "cc87aa3f-a04c-4414-a1b4-8f2ef3592c5e"
migrations_dir = "src/db/migrations"
