/**
 * Content migration script
 * Reads word and passage data and generates a seed.sql file for the D1 database.
 *
 * Usage:
 *   npx tsx scripts/migrate-content.ts
 *
 * Output:
 *   packages/api/seed.sql
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// ---------------------------------------------------------------------------
// Types (local, not imported from shared to keep this script self-contained)
// ---------------------------------------------------------------------------

interface Word {
  id: number
  word: string
  pos: string
  phonetic: string
  zh: string
  en: string
  examples: string[]
  level: string
  topics: string[]
}

interface Passage {
  id: number
  title: string
  genre: string
  text: string
  wordIds: number[]
  level: string
  topic: string
}

// ---------------------------------------------------------------------------
// Load data
// ---------------------------------------------------------------------------

const dataDir = path.join(__dirname, 'data')

const wordsPath = path.join(dataDir, 'b2.json')
if (!fs.existsSync(wordsPath)) {
  console.error(`Missing ${wordsPath}`)
  console.error('Extract it with: git show <commit>:packages/web/src/data/words/b2.json > packages/api/scripts/data/b2.json')
  process.exit(1)
}
const words: Word[] = JSON.parse(fs.readFileSync(wordsPath, 'utf-8'))

const passagesPath = path.join(dataDir, 'passages.json')
if (!fs.existsSync(passagesPath)) {
  console.error(`Missing ${passagesPath}`)
  console.error('Run the extract-passages.js helper first.')
  process.exit(1)
}
const passages: Passage[] = JSON.parse(fs.readFileSync(passagesPath, 'utf-8'))

// ---------------------------------------------------------------------------
// SQL helpers
// ---------------------------------------------------------------------------

/** Escape single quotes for SQL string literals */
function esc(value: string): string {
  return value.replace(/'/g, "''")
}

/** Wrap a string value in single quotes, or return NULL */
function sqlStr(value: string | null | undefined): string {
  if (value == null) return 'NULL'
  return `'${esc(value)}'`
}

/** Serialize a value as a JSON string stored in TEXT column */
function sqlJson(value: unknown): string {
  if (value == null) return 'NULL'
  return sqlStr(JSON.stringify(value))
}

// ---------------------------------------------------------------------------
// Build SQL
// ---------------------------------------------------------------------------

const lines: string[] = []

lines.push('-- ============================================================')
lines.push('-- seed.sql — generated by scripts/migrate-content.ts')
lines.push('-- Run with: wrangler d1 execute english-learning --file=seed.sql')
lines.push('-- ============================================================')
lines.push('')

// Language
lines.push('-- Languages')
lines.push(`INSERT OR IGNORE INTO languages (id, name, native_name) VALUES ('en', 'English', 'English');`)
lines.push('')

// Words
lines.push(`-- Words (${words.length} entries)`)
for (const w of words) {
  const examples = sqlJson(w.examples)
  const topics = sqlJson(w.topics)
  lines.push(
    `INSERT OR IGNORE INTO words (id, language_id, word, pos, phonetic, definition_native, definition_target, examples, level, topics) VALUES (${w.id}, 'en', ${sqlStr(w.word)}, ${sqlStr(w.pos)}, ${sqlStr(w.phonetic)}, ${sqlStr(w.zh)}, ${sqlStr(w.en)}, ${examples}, ${sqlStr(w.level)}, ${topics});`
  )
}
lines.push('')

// Passages + passage_words
lines.push(`-- Passages (${passages.length} entries)`)
for (const p of passages) {
  lines.push(
    `INSERT OR IGNORE INTO passages (id, language_id, title, text, level, topic, genre) VALUES (${p.id}, 'en', ${sqlStr(p.title)}, ${sqlStr(p.text)}, ${sqlStr(p.level)}, ${sqlStr(p.topic)}, ${sqlStr(p.genre)});`
  )
}
lines.push('')

lines.push('-- Passage–word associations')
for (const p of passages) {
  if (!p.wordIds || p.wordIds.length === 0) continue
  for (const wordId of p.wordIds) {
    lines.push(
      `INSERT OR IGNORE INTO passage_words (passage_id, word_id) VALUES (${p.id}, ${wordId});`
    )
  }
}
lines.push('')

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

const outputPath = path.join(__dirname, '..', 'seed.sql')
fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')

const wordCount = words.length
const passageCount = passages.length
const pwCount = passages.reduce((sum, p) => sum + (p.wordIds?.length ?? 0), 0)
console.log(`Generated ${outputPath}`)
console.log(`  ${wordCount} words`)
console.log(`  ${passageCount} passages`)
console.log(`  ${pwCount} passage–word associations`)
